---
- name: Delete Container
  docker:
    name: tomcat
    image: "{{ image_version }}"
    state: absent

- name: Build Docker
  docker_image:
    path: "{{ docker_folder }}"
    name: "{{ image_version }}"
    tag: latest
    nocache: yes

- name: Create Container
  docker:
    name: tomcat
    image: "{{ image_version }}"
    state: started
    net: adop-network
    restart_policy: always
    ports: "{{ ports }}"